# Generated by Django 5.0.3 on 2024-07-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksphere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
