# Generated by Django 5.0.3 on 2024-07-10 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksphere', '0002_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='apikey',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='client_id',
            field=models.CharField(default='blank', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='client_secret',
            field=models.CharField(default='blank', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='service',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='tenant_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
