# Generated by Django 5.0.3 on 2024-07-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksphere', '0004_outlookauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(default='(No subject)', max_length=255),
        ),
    ]
