# Generated by Django 5.0.3 on 2024-07-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksphere', '0004_typingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
